<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        seo()
            ->title('PHP AST Explorer')
            ->site('PHP AST Explorer')
            ->description('A web tool to explore the ASTs generated by PHP-Parser.')
            ->twitterSite('ryangjchandler')
            ->twitterTitle('phpast.com - Explore ASTs generated by PHP-Parser.');
    }
}
